.TH TTYLOG 8 "04 Jun 1999" "" ""
.SH NAME
ttylog \- serial device logger
.SH DESCRIPTION
This program writes everything comes from a serial device
from /dev/tty* onto stdout. You can specify device and baud rate
of the device.
.SH OPTIONS
ttylog follows the GNU command line syntax.
.TP
.B -h, --help
Displays a little help
.TP
.B -v, --version
Version number of ttylog
.TP
.B -b, --baud
Baud rate of the device. Available baud rates:
300, 1200, 2400, 9600, 19200, 38400, 57600 and 115200
.TP
.B -d --device
The serial device. For example /dev/ttyS1
.SH AUTHOR
This manual page was written by Tibor Koleszar <t.koleszar@somogy.hu>,
for the Debian GNU/Linux system.
Last modify: Fri Jun  4 10:36:45 1999

